Add testing by criteria
htmlacademy-htmlcss/1770543-sedona-33 pull request #12
Opened 2022-03-17 11:07 UTC by xolab

2022-03-17 13:45 UTC, pavel-nyukalo requested changes
При фокусе данные элементы "прыгают"
![image](https://user-images.githubusercontent.com/52506235/158821253-f5bb9d1f-a6fe-4737-a81e-7596c32a869e.png)
![image](https://user-images.githubusercontent.com/52506235/158821344-b0e6560a-e741-4bc7-a1c7-9287d27f73d3.png)

Тут немного фокус съхал
![image](https://user-images.githubusercontent.com/52506235/158821425-e5de0851-faee-4f57-82de-dab357585faf.png)

Чтобы фокус попадал на чекбоксы можно сделать так:
```css
.control-input:focus + .control-mark {
...
}
```

Тут фокус тоже немного съехал
![image](https://user-images.githubusercontent.com/52506235/158822078-9064316f-ad01-40a4-af5c-74d42aa064fd.png)

2022-03-17 13:45 UTC, pavel-nyukalo commented on index.html
> +      Седона — небольшой городок в Аризоне,<br />заслуживающий большего!
По стайлгайду академии одиночным тегам не надо закрывающий `/`

2022-03-17 14:15 UTC, xolab commented on index.html
> +      Седона — небольшой городок в Аризоне,<br />заслуживающий большего!
Исправлено

2022-03-18 06:48 UTC, pavel-nyukalo approved these changes

2022-03-18 06:49 UTC, merged