Add Main page with html-markup
htmlacademy-htmlcss/1770543-sedona-33 pull request #2
Opened 2022-01-20 23:53 UTC by xolab

2022-01-21 13:11 UTC, pavel-nyukalo requested changes

2022-01-21 13:11 UTC, pavel-nyukalo commented on index.html
> +          <li class="advantages-item">
Глядя на макет, по семантике вырисовывается, что Жилье, Еда и Сувениры - это отдельный список внутри первого пункта нумерованного списка

![image](https://user-images.githubusercontent.com/52506235/150531764-68c7eda5-089c-4d42-9a80-3ec05b46706e.png)

Сейчас получается это у нас один список. Предлагаю сделать нумерованный список `ol` для блоков с цифрами, а жилье и тд положить списком внутрь первого элемента.

И картинки тоже надо добавить в разметку, они все же контентные

2022-01-21 13:11 UTC, pavel-niukalo commented on index.html
> +          <p class="contacts-phone">+7 (812) 812-12-12</p>
Телефон по [критериям](https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-03) надо разметить ссылкой с соответствующим атрибутом

2022-01-24 15:27 UTC, xolab commented on index.html
> +          <li class="advantages-item">
Исправлено

2022-01-24 15:27 UTC, xolab commented on index.html
> +          <p class="contacts-phone">+7 (812) 812-12-12</p>
Исправлено

2022-01-26 04:14 UTC, pavel-nyukalo requested changes

2022-01-26 04:14 UTC, pavel-nyukalo commented on index.html
> +              </li>
Картинку я бы все-таки лучше вынес в родительский `li`, то есть
```html
li
  h3 Настоящий
  span -№1-
  p ...
  img
  ul ....
```

2022-01-26 04:14 UTC, pavel-nyukalo commented on index.html
> +                <h3 class="advantages-title">Жильё</h3>
По иерархии тут уже идет `h4`

2022-01-26 04:14 UTC, pavel-nyukalo commented on index.html
> +            </ul>
Вот как раз, чтобы не создавать еще один список (тут он не нужен по семантике, но нужен для единообразия) только лишь для картинки

2022-01-26 06:02 UTC, xolab commented on index.html
> +                <h3 class="advantages-title">Жильё</h3>
Исправлено

2022-01-26 06:44 UTC, xolab commented on index.html
> +            </ul>
Исправлено

2022-01-26 06:54 UTC, pavel-nyukalo approved these changes

2022-01-26 06:54 UTC, merged