Add styles for index.html and catalog.html
htmlacademy-htmlcss/1770543-sedona-33 pull request #5
Opened 2022-01-29 23:30 UTC by xolab

2022-01-31 05:43 UTC, pavel-nyukalo requested changes

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +                  </label>
Немного поехали отступы, текст и `input` находятся на одном уровне вложенности в `label`, то бишь:
```html
<label>
  <input
    class....
  >
  Бассейн
</label>
```

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +                    </span>
Здесь так же

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +                />
Для а) единообразия и б) для соответствия [кодгайду](http://codeguide.academy/html-css.html#html-closed-tag) нужно убрать `/` у одиночного тега

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +                </h3>
Так же про вложенность

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +                </h3>
+1

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +            </a>
Чтоб не забылось, тут тоже оставлю

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +            </a>
И тут

2022-01-31 05:43 UTC, pavel-nyukalo commented on catalog.html
> +            </a>
Дело вкуса, но мне кажется если текст в теге не слишком большой, то его можно в одну строчку писать, чтобы не растягивать разметку. Но это повторюсь дело вкуса, не ошибка

2022-01-31 05:43 UTC, pavel-nyukalo commented on styles/styles.css
> +}
По [кодгайду](http://codeguide.academy/html-css.html#css-order) свойства необходимо группировать. Для того, чтобы не вручную это делать, предлагаю использовать CSSComb

2022-01-31 14:37 UTC, xolab commented on catalog.html
> +                />
Исправлено

2022-01-31 14:37 UTC, xolab commented on catalog.html
> +                    </span>
Исправлено

2022-01-31 14:37 UTC, xolab commented on catalog.html
> +                  </label>
Исправлено

2022-01-31 14:38 UTC, xolab commented on catalog.html
> +                </h3>
Исправлено

2022-01-31 14:38 UTC, xolab commented on catalog.html
> +            </a>
Исправлено

2022-01-31 15:31 UTC, xolab commented on catalog.html
> +            </a>
Пока оставил так

2022-01-31 19:54 UTC, xolab commented on styles/styles.css
> +}
Спасибо, использовал!

2022-02-01 08:27 UTC, pavel-nyukalo approved these changes

2022-02-01 08:27 UTC, merged